### ISSUE TITLE
OTM Workflow: Review edits and comments

### ISSUE THREAD

**Issue by diamondap** [ucsdlib/otm-specs#16]
Review the edits and comments in the attached 
[OTM_Workflow.pdf](https://github.com/ucsdlib/otm-specs/files/3871187/OTM_Workflow.pdf). Most of these are typo fixes and requests/suggestions for clarification.

**Comment by mikejritter** [comment]
@diamondap Thanks for the comments, just a few questions from some discussion earlier

> [MOU2]: Can you explain the meaning of this
field and who will find it useful? (DDP, Bridge, Gateway,
Depositor?)

This field will be referenced in the OCFL`inventory.json` and stores the version passed to the Bridge from the Gateway. It seems like this clarification could be provided in the introduction for the Deposit workflow, in the note for the section, or keep it as part of the Chronopolis workflow. I think making a note of it in the introduction makes the most sense, as it will bring to light the fact that there is this version information being propagated through the system. Just wanted more feedback on this before putting the changes in.

> [MOU3]: Is the bridge expected to keep audit
records in its own internal persistent storage? Or can the
DDP keep those records and have the bridge pass through
requests for deletion events and so on? My concern is
keeping two copies of an audit log (DDP and bridge) in sync.

We've been assuming within the working group that the DDP does not need to keep the audit events stored. There have been a few different ideas of how this actually could be implemented, and have tried to keep it so that the bridge can be rebuilt and reconnect to whatever store is there. 

I was considering adding this information to the audit event appendix, but just remembered there's an Audit workflow here as well. The Audit workflow could potentially be promoted so that there's information about where the Audit Log is stored at the beginning of the document.

> [MOU5]: This means the gateway knows what
files constitute each object at each DDP. Is that correct? And
intentional? Again, I worry about keeping inventories in sync
between gateway and multiple DDPs.

It looks like this workflow should have been updated - the Gateway will be querying the Bridge so that it can retrieve the files. So the information will only need to be stored at the Bridge. I'll be updating this and getting some review from Tom to make sure it is proper.

> [MOU7]: Why wait until the TTL expires?
Why not create the event as soon as the restored files are
ready?

We had asked the same question before. Given the responsibilities in the workflow, it makes sense for this to occur when the Bridge is notified that the restore is ready.

**Comment by diamondap** [comment]
Thanks. As long as the docs clarify those things, all is well. I don't think the docs need to say where audit records are stored, just that the bridge is able to return them on request.

**Comment by mikejritter** [comment]
@diamondap I added some clarification to the issues you pointed out which can be viewed at https://github.com/ucsdlib/otm-specs/pull/24

**Comment by mikejritter** [comment]
Merged in #24
