### ISSUE TITLE
Add Status Of This Document

### ISSUE THREAD

**Issue by no-reply** [ucsdlib/otm-specs#47]
Communicate about the status of the specs: there is no implementation, the design goals have been to capture the use cases and interaction patterns needed to meet them. We assume further spec versions would be an outcome of an implementation phase.

**Comment by bbranan** [comment]
Notes from this discussion:
- Objective of the specification: Make it clear that the goal is to provide the structure and capture the required interactions so that teams that are building these systems (while communicating with each other) would be able to implement
- Deeper details will need to be defined by the development teams
- Trying to leave some flexibility in the design to facilitate development
- Add something to the README (status of this document section)
