### ISSUE TITLE
Comment on failure states

### ISSUE THREAD

**Issue by no-reply** [ucsdlib/otm-specs#48]
Recovery guarantees are focused on recovery for successful deposits. it should be possible to recover objects into a repository from only the DDP in case of failure of all other components.

**Comment by bbranan** [comment]
Other notes to include:
- There are no explicit guarantees of a file or object being recoverable if it has not completed the deposit process
- The Bridge maintains processing state that, if lost, may necessitate a re-start of deposit transfers
- The Bridge maintains audit details as a cache for details stored in the DDP. This audit information is expected to remain in the DDP such that a restore could be performed if the Bridge were to fail. The DDP is not expected to maintain this data in a format that facilitates easy access (that's why the Bridge cache exists).
